services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/code
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./cabin_site
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./cabin_site:/code
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
