# Generated by Django 5.0.6 on 2024-07-04 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cabin_site", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cabin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=2)),
                ("city", models.CharField()),
                ("things_to_do", models.TextField()),
                ("listing_url", models.URLField()),
                ("image_url", models.URLField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name="trip",
            name="cabins",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cabin_site.cabin",
            ),
            preserve_default=False,
        ),
    ]
