# Generated by Django 5.0.9 on 2024-12-12 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cabin_site", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="birth_date",
        ),
    ]
