# Generated by Django 5.0.9 on 2024-12-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cabin_site", "0002_remove_user_birth_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(unique=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, null=True)),
            ],
        ),
    ]
