# Generated by Django 5.0.6 on 2024-07-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cabin_site", "0002_cabin_trip_cabins"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("unique_id", models.UUIDField()),
            ],
        ),
        migrations.AddField(
            model_name="cabin",
            name="votes",
            field=models.ManyToManyField(
                blank=True, related_name="votes", to="cabin_site.user"
            ),
        ),
    ]
