# Generated by Django 5.0.6 on 2024-07-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cabin_site", "0004_alter_trip_cabins"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="year",
            field=models.IntegerField(unique=True),
        ),
    ]
