# Generated by Django 5.0.6 on 2024-07-06 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cabin_site", "0005_alter_trip_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="cabin",
            name="submitter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="cabin_site.user",
            ),
        ),
    ]
