# Generated by Django 5.0.9 on 2024-12-12 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cabin_site", "0005_alter_cabin_price_alter_cabin_trip"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
