# Generated by Django 5.0.6 on 2024-07-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cabin_site", "0006_cabin_submitter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cabin",
            name="things_to_do",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="trip",
            name="cabins",
        ),
        migrations.AddField(
            model_name="trip",
            name="cabins",
            field=models.ManyToManyField(blank=True, null=True, to="cabin_site.cabin"),
        ),
        migrations.AlterField(
            model_name="trip",
            name="cabins",
            field=models.ManyToManyField(blank=True, to="cabin_site.cabin"),
        ),
    ]
