# Generated by Django 5.0.9 on 2024-12-13 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cabin_site", "0006_remove_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="year",
        ),
    ]
