# Generated by Django 5.0.6 on 2024-07-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cabin_site", "0007_alter_cabin_things_to_do_remove_trip_cabins_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cabin",
            name="price",
            field=models.IntegerField(default=0),
        ),
    ]
