# Generated by Django 5.0.9 on 2024-12-13 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cabin_site", "0007_remove_trip_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cabin",
            name="trip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cabins",
                to="cabin_site.trip",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="name",
            field=models.CharField(),
        ),
    ]
