# Generated by Django 5.0.9 on 2024-12-15 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cabin_site", "0008_alter_cabin_trip_alter_trip_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="is_active",
            field=models.BooleanField(db_default=True),
        ),
        migrations.AlterField(
            model_name="cabin",
            name="submitter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
