# Generated by Django 5.0.6 on 2024-07-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cabin_site", "0008_cabin_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cabin",
            name="image_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="cabin",
            name="listing_url",
            field=models.URLField(max_length=1000),
        ),
    ]
