# Generated by Django 5.0.9 on 2024-12-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cabin_site", "0009_trip_is_active_alter_cabin_submitter"),
    ]

    operations = [
        migrations.AddField(
            model_name="cabin",
            name="is_active",
            field=models.BooleanField(db_default=True),
        ),
    ]
