# Generated by Django 5.0.6 on 2024-07-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cabin_site", "0009_alter_cabin_image_url_alter_cabin_listing_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="final_round_cabins",
            field=models.ManyToManyField(
                blank=True, related_name="final_round_cabins", to="cabin_site.cabin"
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="in_final_voting_round",
            field=models.BooleanField(default=False),
        ),
    ]
